### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by mj-e-boc**
-Page titles - NO issues found 
-Image text alternatives - no issues found 
-Headings - changed h3 heading on line 43 https://github.com/mj-e-boc/Ronald-Portfolio/blob/50b934e7b399bc3ddcd8731d88d19009fafd300e/index.html#L43  to h2 since parent heading was h1
- Color contrast - No issues found
- Resize, changed font sizes line 393-430 https://github.com/mj-e-boc/Ronald-Portfolio/blob/50b934e7b399bc3ddcd8731d88d19009fafd300e/styles.css#L392-L430 css, for when screen enlarges so text is still big enough for better UX , accessibility improvements.
- Interaction - no issues found 
- Multimedia - NO issues found
- The basic structure of the page - No issues found

### CODE REVIEW

**Review by Gopxfs — CHANGES_REQUESTED** [review]
# ♻️ STATUS: REQUIRED CHANGES ♻️

## Hi team 👋,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



## Highlights :rocket:
✔️ No linter errors.
✔️ Great code structure. Well done!
✔️ Nice update with some accessibility elements.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions 🗒️  
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @Gopxfs in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gopxfs** [comment]
As requested in the project requirements:
image

Your PR description should contain a report with these bullet points, and the result of your evaluation 😉:
image

Please make sure to include your reported changes on your pull request description 😄!

**Comment by Gopxfs** [comment]
https://github.com/mj-e-boc/Ronald-Portfolio/blob/dcdc1b4fe345afdb8b050cf5080dc71b7ac9b31e/index.html#L36-L43
As [explained here](https://www.w3.org/WAI/test-evaluate/preliminary/#headings), your headings should have a meaning hierarchy 😄! Please update this `h3` to a `h2`, since its parent header is a `h1`.

**Review by brainconnect93 — CHANGES_REQUESTED** [review]
## STATUS: Changes Required :recycle:

### Hi @mj-e-boc, 👋

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [ ] As suggested by the previous reviewer, while you did highlight the changes you made on the pull request, the requirement was to include a [link to the corresponding line of code in your pull request changes](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148). The hyperlink has a precise process to do that. kindly make the suggested changes on all issues you fixed, so it can lead to the exact line of code you changed.

- [ ] Send this same PR for review on your dashboard when you're done 👍

### Instructions





- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by RaoAkif — CHANGES_REQUESTED** [review]
## STATUS: REQUIRED CHANGES ♻️

Hi Team, 

It is necessary to implement all the changes suggested by the previous reviewer, before asking for another review so that you could improve your project and make some progress. As mentioned by the previous reviewer the requirement was to include a [link to the corresponding line of code in your pull request changes](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148). The hyperlink has a precise process to do that. kindly make the suggested changes on all issues you fixed, so it can lead to the exact line of code you changed.


## Highlights
✔ Linters are on point 
✔ Splendid work with the README file
✔ Great use of GitHub flow
✔ Good code design and implementation

## Required Changes ♻️
_Check the comments under the review._


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by leonardodiasb — APPROVED** [review]
# Status: ✔️ Project Approved ✔️ 

Hello @mj-e-boc 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

 - ✔️ No linter errors.
 - ✔️ Great code structure. Well done!
 - ✔️ Nice update with some accessibility elements.
 - ✔️ Professional report.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
